"""AES-256-GCM sealing for clipboard payloads.

Wire format (identical to mobile/src/lib/crypto.ts):

    base64( nonce[12] || ciphertext || tag[16] )

The room id is passed as additional authenticated data, so a ciphertext
lifted out of one room cannot be replayed into another: the tag check fails
before any plaintext is produced.

The key is 32 raw bytes generated by ``os.urandom`` on the desktop and moved
to the phone through the pairing QR. It is never transmitted to the server.
"""

from __future__ import annotations

import base64
import os
from typing import Final

from cryptography.exceptions import InvalidTag
from cryptography.hazmat.primitives.ciphers.aead import AESGCM

KEY_BYTES: Final[int] = 32   # AES-256
NONCE_BYTES: Final[int] = 12  # 96-bit nonce, the GCM standard
TAG_BYTES: Final[int] = 16

# A single key must not be used for more than 2^32 random 96-bit nonces.
# Clipboard traffic is nowhere near that, but the room key is rotatable by
# re-pairing if a device ever approaches it.
MAX_PLAINTEXT_BYTES: Final[int] = 128 * 1024


class DecryptionError(Exception):
    """Raised when a payload is malformed, truncated, or fails its auth tag."""


def generate_key() -> bytes:
    """Return a fresh 32-byte AES-256 key from the OS CSPRNG."""
    return os.urandom(KEY_BYTES)


def encode_key(key: bytes) -> str:
    """Serialise a raw key to standard base64 (what goes into the QR)."""
    _check_key(key)
    return base64.b64encode(key).decode("ascii")


def decode_key(encoded: str) -> bytes:
    """Parse a base64 key, validating its length."""
    try:
        key = base64.b64decode(encoded, validate=True)
    except (ValueError, TypeError) as exc:
        raise ValueError("key is not valid base64") from exc
    _check_key(key)
    return key


def encrypt(key: bytes, plaintext: str, room_id: str) -> str:
    """Seal ``plaintext`` for ``room_id`` and return the base64 wire payload."""
    _check_key(key)
    data = plaintext.encode("utf-8")
    if len(data) > MAX_PLAINTEXT_BYTES:
        raise ValueError(
            f"payload of {len(data)} bytes exceeds the {MAX_PLAINTEXT_BYTES} byte limit"
        )

    nonce = os.urandom(NONCE_BYTES)
    sealed = AESGCM(key).encrypt(nonce, data, _aad(room_id))
    return base64.b64encode(nonce + sealed).decode("ascii")


def decrypt(key: bytes, payload: str, room_id: str) -> str:
    """Open a base64 wire payload produced by :func:`encrypt` (or its TS twin)."""
    _check_key(key)
    try:
        raw = base64.b64decode(payload, validate=True)
    except (ValueError, TypeError) as exc:
        raise DecryptionError("payload is not valid base64") from exc

    if len(raw) < NONCE_BYTES + TAG_BYTES:
        raise DecryptionError("payload is too short to contain a nonce and tag")

    nonce, sealed = raw[:NONCE_BYTES], raw[NONCE_BYTES:]
    try:
        plaintext = AESGCM(key).decrypt(nonce, sealed, _aad(room_id))
    except InvalidTag as exc:
        raise DecryptionError(
            "authentication failed: wrong room key, wrong room, or tampered payload"
        ) from exc

    try:
        return plaintext.decode("utf-8")
    except UnicodeDecodeError as exc:  # pragma: no cover - only on corrupt input
        raise DecryptionError("plaintext is not valid UTF-8") from exc


def fingerprint(key: bytes) -> str:
    """Short, non-reversible key identifier for the pairing UI.

    Shown on both screens so a user can confirm the two devices really do hold
    the same key. Derived through SHA-256, so it leaks nothing usable.
    """
    from cryptography.hazmat.primitives import hashes

    _check_key(key)
    digest = hashes.Hash(hashes.SHA256())
    digest.update(b"clipsync-key-fingerprint-v1")
    digest.update(key)
    raw = digest.finalize()[:5]
    alphabet = "23456789ABCDEFGHJKLMNPQRSTUVWXYZ"  # Crockford-ish, no look-alikes
    value = int.from_bytes(raw, "big")
    chars = []
    for _ in range(8):
        chars.append(alphabet[value % len(alphabet)])
        value //= len(alphabet)
    out = "".join(reversed(chars))
    return f"{out[:4]}-{out[4:]}"


def _aad(room_id: str) -> bytes:
    if not room_id:
        raise ValueError("room_id is required as additional authenticated data")
    return room_id.encode("utf-8")


def _check_key(key: bytes) -> None:
    if not isinstance(key, (bytes, bytearray)) or len(key) != KEY_BYTES:
        raise ValueError(f"AES-256 key must be exactly {KEY_BYTES} bytes")
